OBJS = main.o \
bg.o character.o finalscreen.o flirtbutton.o gamescreen.o  look.o lookbutton.o lovebar.o \
menubar.o move.o movebutton.o selectionrectangle.o talk.o talkbutton.o talkselect.o titlescreen.o